### ISSUE TITLE
Hiding the Selected Option From the Dropdown List

### ISSUE THREAD

**Issue by benlevywebdesign** [Robdel12/DropKick#363] opened 2018-06-02 18:31 UTC
### Version of Dropkick:

2.1.7

### Expected Behavior

I would like to be able to hide the selected option from the list of the other options so it only shows once.
For example, if yes is the selected option, I only want the "disabled placeholder" and "no" to show.
<img width="348" alt="selectoptions" src="https://user-images.githubusercontent.com/6495066/40929904-f6cd1900-67da-11e8-8a63-c91f806f2cfb.png">

### Actual Behavior

<img width="348" alt="hideselected" src="https://user-images.githubusercontent.com/6495066/40879666-3eefb690-6658-11e8-8040-02121c8e40c6.png">

**Comment by Robdel12** [comment] 2018-06-04 14:44
Hey @benlevywebdesign! Would you be able to apply a class to the selected option that hides it?

**Comment by benlevywebdesign** [comment] 2018-06-04 16:39
@Robdel12 I updated my question.

**Comment by acemir** [comment] 2018-06-06 02:55
@benlevywebdesign Setting `.dk-option-selected` to `display: none;` should resolve the issue.

**Comment by benlevywebdesign** [comment] 2018-06-11 15:04
@acemir I want the selected option to stay. The selected option also shows up in the choices below the disabled placeholder option.

If the choices are: **Choose One(placeholder), Yes, No, Maybe** and the selected choice is "Yes" then I don't want to see "Yes, Choose One, Yes, No, Maybe".

**Comment by Robdel12** [comment] 2018-06-11 15:50
Oh wait, that's actually interesting. How does that happen? You're getting a duplicate of the selected option?

**Comment by benlevywebdesign** [comment] 2018-06-11 17:13
It's on forms when I get the selected value from the database. See code below:
<img width="346" alt="dropkick" src="https://user-images.githubusercontent.com/6495066/41246075-c547b398-6d5e-11e8-84ba-a9f0ea2a6699.png">
```
<select class="selectoptions_ma" id="imageuploaded" name="imageuploaded">
<option selected value='<?php echo $imageuploaded ?>'> <?php echo ($imageuploaded == '1') ? Yes : No ?></option>
<option value="" disabled="disabled">Image Uploaded?</option>
<option value="1">Yes</option>
<option value="0">No</option>
</select>
```

____

How would I either make the selected value be from the order of the list or take it out and only show the non selected options below the placeholder?

<img width="344" alt="dropkick2" src="https://user-images.githubusercontent.com/6495066/41246240-4dae4f1c-6d5f-11e8-888f-985df891a5ca.png">
or
<img width="348" alt="40929904-f6cd1900-67da-11e8-8a63-c91f806f2cfb" src="https://user-images.githubusercontent.com/6495066/41246244-514a2b28-6d5f-11e8-9f51-e99ade13261c.png">

**Comment by Robdel12** [comment] 2018-06-11 17:45
Ahh, I see what you're going for now. From the example code you gave I'd write the select like this:

```html
<select>
  <option value="" disabled="disabled">Image Uploaded?</option>
  <option <?php echo ($imageuploaded == '1') ? 'selected' : '' ?> value="1">Yes</option>
  <option <?php echo ($imageuploaded == '0') ? 'selected' : '' ?> value="0">No</option>
</select>
```

That will have two selectable options in the list and it will select the right one given the value from the DB (`$imageuploaded`).

**Closed** 2018-06-11 22:28 UTC
Labels: Investigate
